### ISSUE TITLE
Rice is not complete yet 

### ISSUE THREAD

**Issue by davidnoronha1** [FrenzyExists/Nord-dotfiles-i3#1]
pls fix

**Comment by FrenzyExists** [comment]
I'll update it to the current one i have, as its somewhat different now. I'll try on the night as I'm currently studying 👍

**Comment by davidnoronha1** [comment]
I opened issue as joke, do when you have time

**Comment by FrenzyExists** [comment]
I am opening this issue, and **Y E S**, I gonna work on these old dotfiles, on my old laptop tho since on my main one I'm working on the Aquarium dotfiles

**Comment by davidnoronha1** [comment]
Intereseting!
